name: Node.js App CI

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2️⃣ Extract Owner and Repo from github context
      - name: Set Owner and Repo env variables
        run: |
          REPO_FULL=${{ github.repository }}
          OWNER=$(echo "$REPO_FULL" | cut -d'/' -f1)
          REPO=$(echo "$REPO_FULL" | cut -d'/' -f2)
          echo "OWNER=$OWNER" >> $GITHUB_ENV
          echo "REPO=$REPO" >> $GITHUB_ENV

      # 3️⃣ Test
      - name: Test
        uses: zakarialaoui10/master@main

      # 4️⃣ Run Node.js script
      - name: Run Node Script
        run: node scripts/index.js

      # 5️⃣ Commit and Push changes
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated" || echo "No changes to commit"
          git push https://x-access-token:${CUSTOM_TOKEN}@github.com/$OWNER/$REPO.git
        env:
          CUSTOM_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
